# Generated by Django 5.1.4 on 2025-01-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, choices=[('report', 'Report a scam'), ('consult', 'Consult an expert')], max_length=20)),
                ('country_code', models.CharField(blank=True, max_length=5)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('scam_type', models.CharField(blank=True, choices=[('phishing', 'Phishing'), ('identity_theft', 'Identity Theft'), ('online_fraud', 'Online Fraud')], max_length=20)),
                ('amount_lost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('case_outline', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
