# Generated by Django 5.1.4 on 2025-01-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_investmentdata_delete_formsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentdata',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='investmentdata',
            name='investment_amount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='investmentdata',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='investmentdata',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
